### PR TITLE
add email to moderator page

### PR DESCRIPTION
**Pull request by BHydden**
## Proposed Changes

  - Attempt to add an email column for new users in moderator page

### CODE REVIEW

**Comment by BHydden** [comment]
I confirmed that user.email is the correct name for the field, but the column isn't populating in my tests. Any thoughts on what I'm missing?

**Comment by mattetress** [comment]
It's hard for me to help without being able to test it out directly for myself, but does the email heading show and not the emails or do you get neither?

**Comment by BHydden** [comment]
The header shows its just the data that doesn't populate. Eugene helped me realise that email isn't an element of X as I had wrongly assumed, looking into an alternate path to access it.

**Comment by BHydden** [comment]
Still working on this but nothing wish pushing up yet, mostly walking in circles sadly.

**Comment by anoek** [comment]
I am pretty sure this is going to need some server side support to add that field for you, I don't typically return that field anywhere since it's sensitive information.

**Comment by BHydden** [comment]
Yeah I was concerned that was the case. It can be accessed through the moderator modal on the profile page so I was hoping I could replicate that somehow.

**Comment by anoek** [comment]
Thanks for the PR, sorry it took so long to get to the backend part

**Comment by BHydden** [comment]
I didn't realise you were planning on doing it so soon! Thank you!!! 😍😍😍

**Pull request merged**
