### PR TITLE
issue-2275: reduce clickable area for invite-only games

### LINKED ISSUE #2275: Move the Invite-only checkbox (or clickable area) to stop it being checked by mistake on small screen devices
See https://forums.online-go.com/t/invite-only-by-mistake/48114

Will experiment with a few options.

### PR DESCRIPTION
**Pull request by andymarden**
Fixes #2275 

## Proposed Changes
Simple change in ChallengeModel.tsx to remove the htmlFor tag from the label alongside the checkbox, making it none-clickable 
  -
  -
  -

### CODE REVIEW

**Comment by anoek** [comment]
For consistency with everywhere else, I think the htmlFor should remain. I think we should probably fix this issue by moving that checkbox somewhere else so it's not easy to click by accident, or give it some more margin.

**Comment by andymarden** [comment]
If that is what's required, I think I will move it to to the section above the Create Game button - personally I don't feel it is useful for most people to leave the htmlfor in since it is likely to be relatively rare when you want to switch between these but happy to do so.

Another option has just occurred to me - there is easily enough space have a "Create Open Game" and a "Create Private Game" next to each other horizontally where the existing button is, rather than have to remember to click on and off a check box.

What do we think?

**Comment by anoek** [comment]
Yeah moving it above is the right thing to do I think, under `Private` maybe?

**Comment by andymarden** [comment]
OK - will do that

**Comment by andymarden** [comment]
OK - done - now under Private - I agree that's much better

**Comment by anoek** [comment]
Cool looks good, though I'm seeing a lot of other commits here too, could you try rebasing your changes to see if that clears all of those up?

**Pull request closed without merging**
