### PR TITLE
Accessibility theme

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes the problem that we use very unfriendly colours for colourblind people.

## Proposed Changes

Add a theme and tweak the colours.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Ooops, I got my previous changes tangled up in here doh!

This is a prototype at this point.

**Comment by GreenAsJade** [comment]
@anoek I think this much is useful to see on Beta.

**Comment by anoek** [comment]
No problem, it's up on beta @GreenAsJade

**Comment by GreenAsJade** [comment]
I think this is ready for merge - it gives an accessible theme, based on dark, with themed presence indicators.

I'll check in win/loss color theming in due course, separately.

**Comment by anoek** [comment]
Thanks for this!

**Comment by mmartin** [comment]
Hi, @GreenAsJade!

After this PR the presence indicator has a white top-left corner in the dark theme –
image

Was this an intended change or an accident?

**Comment by GreenAsJade** [comment]
Curiously, I recall seeing that there and thinking it was in the original, deliberately "leaving it there".

So I must have introduced it by accident along the way I guess :shrug:

**Pull request merged**
