### PR TITLE
Added a "None" option for board label lettering

### LINKED ISSUE #2802: relocate global toggle for coordinatea
**Describe the bug**
Global toggle for coordinates is in the game menu, when all other items in that menu pertain to the specific game.

**Expected behavior**
Make `None` an option in [board label lettering](https://online-go.com/settings/theme)

**Additional context**
https://forums.online-go.com/t/new-experimental-svg-based-goban-renderer/51831/93?u=bhydden

### PR DESCRIPTION
**Pull request by andywng**
Fixes #2802

## Proposed Changes

  - Add a `None` option for board label lettering. This provides the option of a cleaner looking board.

### CODE REVIEW

**Comment by andywng** [comment]
This change in the goban repo has to go in before this change will work: https://github.com/online-go/goban/pull/174

**Comment by benjaminpjones** [comment]
Should this "None" option also hide the "Toggle Coordinates" button in the game dock?

https://github.com/online-go/online-go.com/blob/2282ff03ee06dd78e3b170ea541f4ea351ce15f7/src/views/Game/GameDock.tsx#L372-376

**Comment by anoek** [comment]
This seems redundant with the None option in Board label positioning, which turns off the board labels

image

**Comment by BHydden** [comment]
> None option in Board label positioning

I think with the OGS  settings cockpit meme, none of us knew of this until now 😅 I will mention it in the relevant forum thread. As you say, this probably resolves the issue

**Comment by anoek** [comment]
Yeah, generally speaking two places to control the same thing isn't a great user experience. Generally speaking, just pick one, and since we already have one, I'm not sure it makes sense to add another one.

If there y'all feel strongly that this menu should have it I would second the need to have the "None" status linked with the position control so that they are either both None or both not None, but never just one.

**Comment by anoek** [comment]
Closing as resolved with the board label position None option

**Pull request closed without merging**
