### PR TITLE
Revised profanity_filter.ts

### PR DESCRIPTION
**Pull request by felixthelucas**
Older, pre-ES6 browsers don't supported the u flag, enabled to handle some accented words in the Portuguese filter. In order to ensure backward compatibility, I've disabled the flag and removed unicode entries from the list altogether.

Not the ideal solution, but it should work for the time being.

More information: Issue #758.

### CODE REVIEW

**Comment by anoek** [comment]
If the `u` is useful, you could just do

try { 
profanity_regex["pt"] = new RegExp("...", "igu");
catch (e) {
profanity_regex["pt"] = new RegExp("..", "ig");
}

**Comment by anoek** [comment]
If you decide to do the try / catch stuff I'd be happy to merge that as well :) Thanks for the quick fix here.

**Comment by felixthelucas** [comment]
It is, @anoek. This fix will do for now, but I'll see if I can download some older browsers and run them with WINE to do some testing with a try/catch. Thank you very much and sorry for the trouble.

**Comment by anoek** [comment]
No problem at all :)

**Pull request merged**
