### PR TITLE
Balance dark theme white player colour

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes colour mismatch between ordinary white and black player in dark theme.

## Proposed Changes

Reduce the darkening of white player colour in the white player container, so the colour looks much more similar.

Current:

Screen Shot 2019-12-12 at 9 08 48 pm (2)

Proposed:

Screen Shot 2019-12-12 at 9 40 51 pm (2)

### CODE REVIEW

**Comment by BHydden** [comment]
Isn't darker easier to read? Even if an optical illusion makes it look darker than for black?

**Comment by GreenAsJade** [comment]
Yes, this is exploring the tradeoff between "max readability" and "wait, are these two players the same type, or different?"

I presume you have fired up this changed and checked it in real life?

I find this change very readable, and much more pleasing because the colours appear the same.

But ... we know what my eyes are like 😬

**Comment by BHydden** [comment]
You presume wrong. My feedback is based solely on your provided screenshots.

**Comment by GreenAsJade** [comment]
Ah :)   Well, I think experience has shown us that to assess the quality of the solution, you have to see the actual thing.

The screenshots just convey the idea of what has been done.

**Comment by GreenAsJade** [comment]
In assessing this, I think it's important to take into consideration that readability is not the only factor.

The colour of player names conveys significant meaning, so it is important for this to be honoured.

The "blue" color is not there because it is the best color for that screen.  It's there because it means "unpaid user".   Adding "dark blue" confuses the issue...

**Comment by anoek** [comment]
I dunno, I agree that the new blue is kind of hard to read. Maybe there's something in between?

**Comment by GreenAsJade** [comment]
My eyes strike again 😬 

I'll try to find something better contrasting but also more similar looking in some way to the black player colour.  Suggestions welcome ...

**Comment by GreenAsJade** [comment]
Screenshot deliberately not attached: please check "in situ".

**Comment by anoek** [comment]
It's up on beta for anyone who want's to take a look: https://beta.online-go.com/game/6632 for an example game

**Comment by BHydden** [comment]
That one looks pretty good. I think the colours match pretty well.

**Comment by GreenAsJade** [comment]
Yay thank goodness, me too 😁

**Comment by anoek** [comment]
Closing as per your instruction

**Pull request closed without merging**
