### PR TITLE
chat substitution: allow # in front of numbers

### PR DESCRIPTION
**Pull request by flovo**
now matches `player #123`, ...
don't `match #123` => `game 123` anymore.

### CODE REVIEW

**Comment by BHydden** [comment]
will this break its implementation in PM? I use #{gameId} very often in my mod PMs

**Comment by flovo** [comment]
Not tested, but if my observations are correct, none of my changes applies to pm and game chat. I'm planning to make it work through.

**Comment by BHydden** [comment]
In theory, if the things you add don't bleed through, the things you remove shouldn't either... but definitely worth testing to make sure before it goes live :)

**Comment by flovo** [comment]
I don't get it to match `#<number>` as `game<number>` only when it's not matched by anything else without rewriting the whole `chat_mtach`.

**Comment by anoek** [comment]
Thanks!

**Pull request merged**
