### PR TITLE
Cleanup start time typing

### PR DESCRIPTION
**Pull request by GreenAsJade**
#1263 had to work around start-time and end-time not being declared in GoEngineConfig.

https://github.com/online-go/goban/pull/12  will enable this PR to clean that up.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Oh darn, I got #1263 mixed into this one - do I need to do anything to disentangle?

**Comment by GreenAsJade** [comment]
This fails shippable because it needs the goban update.

**Comment by GreenAsJade** [comment]
(Maybe it makes sense that this PR branch is tacked on the end of #1263 branch, since it only applies if that branch is applied).

**Comment by anoek** [comment]
Thanks!

**Pull request merged**
