### PR TITLE
Reduce min rank from 25k to 35k

### LINKED ISSUE #1127: Fully implement ranks down to 35k (With no change to Glicko2)
**Is your feature request related to a problem? Please describe.**
OGS functionality is limited for users below 25k.

**Describe the solution you'd like**
Use existing Glicko2 info to implement ranks down to 35k.

**Describe alternatives you've considered**
Maybe just 30k but that might involve coming back to the issue all over again. 35k should cover it based on rank distribution.

**Additional context**
Forums discussion here: https://forums.online-go.com/t/recognising-and-fully-implementing-ranks-beyond-25-kyu/27079.

### PR DESCRIPTION
**Pull request by BHydden**
Fixes #1127

## Proposed Changes

  - Lower minimum rank from 25k to 35k as per discussion in [the forums](https://forums.online-go.com/t/recognising-and-fully-implementing-ranks-beyond-25-kyu/27079)

Change tested by @GreenAsJade

### CODE REVIEW

**Comment by GreenAsJade** [comment]
I'll post some screenshots shortly

**Comment by GreenAsJade** [comment]
Screen Shot 2020-05-04 at 9 46 03 am (2)
Screen Shot 2020-05-04 at 9 41 01 am (2)
Screen Shot 2020-05-04 at 9 38 11 am (2)
Screen Shot 2020-05-04 at 9 36 54 am (2)
Screen Shot 2020-05-04 at 9 31 34 am (2)
Screen Shot 2020-05-01 at 2 13 32 pm
Screen Shot 2020-04-27 at 5 45 53 pm

**Comment by BHydden** [comment]
> Screen Shot 2020-05-01 at 2 13 32 pm Screen Shot 2020-04-27 at 5 45 53 pm

I think the last two images failed to upload

**Comment by BHydden** [comment]
I think the last two images failed to upload?

**Comment by GreenAsJade** [comment]
There were only 5, I'm not quite sure what happened (I just dragged and dropped) and don't dare to edit it in case I lose them :)

**Comment by GreenAsJade** [comment]
Note: I haven't tested what effect this has on matchmaking, ladders & tournament eligibility.    Might be easiest done on Beta?

**Comment by flovo** [comment]
What happens to the rank selection in the custom challenge dialog?

> Note: I haven't tested what effect this has on matchmaking, ladders & tournament eligibility.

My guesses are:
- Ladders don't care about ratings
- Tournaments participants rank limit is enforced by the server. I'd be surprised if it wouldn't cap ranks at 25k. Same for McMahon bars. Pairing methods already use rating, so I wouldn't expect anything strange there.
- Matchmaking:
    - Quick match finder will still use 25k as lowest rank.
    - Not sure if you can get custom games to work with ranks below 25k.
    - Handicap Auto still uses 25k as lowest rank.

**Comment by BHydden** [comment]
I haven't finished digging... but this code snippet I found indicated there might be problems attempting to go below 29k (rank 1) as I think special things happen at rank 0 (30k)... @anoek  will definitely need to advise on how complicated this could potentially be...

https://github.com/online-go/online-go.com/blob/ad7b3ac16109c3b0f12e299f99fc55de11ff5029/src/components/Player/Player.tsx#L246-L249

**Comment by BHydden** [comment]
> Matchmaking:
> * Quick match finder will still use 25k as lowest rank.
> * Not sure if you can get custom games to work with ranks below 25k.
> * Handicap Auto still uses 25k as lowest rank.

All of these use the user's rank without any bounds, it's the user's rank itself which is bound within rank_util by the code line I changed

McMahon bars I haven't confirmed yet but I suspect they're the same...

My main concern is that things can mean something weird in programming when they = 0 and to get ranks below 29k we need to pass into and through "rank 0" which could have unforeseen consequences... other than that, I think it should all work out... 

I think worst case scenario, I can't see a reason why we couldn't make MinRank = 1 with no ill effects and just have to deal with not having ranks below 29k (which is still much better than only going down to 25k)

**Comment by BHydden** [comment]
Closing this PR pending any significant findings from [the new discussion regarding handicap stones](https://forums.online-go.com/t/recognising-and-fully-implementing-ranks-beyond-25-kyu/27079/99?u=bhydden).

**Pull request closed without merging**
