### PR TITLE
Game history rengo merge

### PR DESCRIPTION
**Pull request by benjaminpjones**
Implements https://forums.online-go.com/t/rengo-status/40415/483

## Proposed Changes

  - Refactor game_history_groomer: this function was really long (120 lines!), so I broke out some logical functions.  It's still pretty long but now it's half the length and fits on one "page".
  - Make the normal columns handle rengo games (sort of)
  - Remove the rengo-specific table
  - Add some types to the Game History table

## Notes

I could use some API support:

- player lists or at least number of players for rengo matches
- ~~Fix the game result fields (black_lost, white_lost)~~ i hear a fix is in flight :)
- include the player whose page we are on in the `game.players` and `game.historical_ratings` (currently it just picks a player at random from each team?)

Screen Shot 2022-02-05 at 12 58 20 AM

(screenshot from [Sophiam's page](https://beta.online-go.com/player/1775))

### CODE REVIEW

**Comment by GreenAsJade** [comment]
> I could use some API support:
>  
>  * player lists or at least number of players for rengo matches

I submitted a fix for this.

> include the player whose page we are on in the game.players and game.historical_ratings (currently it just picks a player at random from each team?)

Pseudo random of course.  I _think_ it is the first players on each team :) 

This looks to need some thought from anoek, due to gotchas (we only have those two player's full details at the time this is being serialised)   

We could easily make it send nothing instead?

**Comment by benjaminpjones** [comment]
>> - player lists or at least number of players for rengo matches
>I submitted a fix for this.

Awesome, thanks!

> We could easily make it send nothing instead?

If there are significant technical barriers, I suppose nothing is fine, but if we want to populate the rank column consistently, I think the player-of-interest needs to show up in the `historical_rankings` somehow.

Screen Shot 2022-02-05 at 4 12 15 PM

**Comment by GreenAsJade** [comment]
I have a path forward to deliver the historical rating for the person who's page we are on.

The weird thing is that this api also returns the ratings for the player of the "other" colour.    In that case, I think I continue to return the "random" player in the "opposite" field - what else could it be?

**Comment by benjaminpjones** [comment]
>I have a path forward to deliver the historical rating for the person who's page we are on.

Woo awesome! Thanks for the help with this, I didn't realize there was backend support needed when I started, but I think the changes you're adding will really make this sparkle :)

> The weird thing is that this API also returns the ratings for the player of the "other" colour. In that case, I think I continue to return the "random" player in the "opposite" field - what else could it be?

For normal games, the ratings are shown in the opponent column so I think that makes sense.  For rengo though, yeah I don't think I can logically show an "opponent" so random player (or no player) in that field is fine as far as the game history goes.

**Comment by anoek** [comment]
@benjaminpjones I just pushed up @GreenAsJade 's API support for you to beta so you can validate things are behaving as you expect and whatnot. I'm gonna mark this as draft, when you've banged on it against the beta API and things are working as expected mark as ready for merge

**Comment by benjaminpjones** [comment]
@anoek Sounds good!  Just so I understand the backend changes, past games haven't been corrected right?  I'll need to examine new rengo matches to see the changes?

Also, possibly related: when I go to beta.online-go.com I get a 500 error.  The site still functions but I see the pop up when I visit the homepage.

**Comment by anoek** [comment]
Sorry, beta should be fixed now, I forgot to run a migration.

I *think* the way @GreenAsJade wrote it, it should work for past games too.. but don't hold me to that :)

**Comment by benjaminpjones** [comment]
Awesome, thanks!  API looks good, I'll need to make some minor changes to get the new information to show up.

**Comment by GreenAsJade** [comment]
... it's definitely the case that _lost is computed at game completion, so won't be fixed by the code change, but ought to be correct now for new games.

Nice table :)    I kinda liked "fun was had", in sending the right message, but I guess ... my fun was had :D

**Comment by GreenAsJade** [comment]
^^ confirmed, it is "end_game_task", which runs once, that calculates and saves _lost.

**Comment by anoek** [comment]
Great work again @benjaminpjones :)

**Pull request merged**
