### PR TITLE
Fix missed accessible theme delta

### LINKED ISSUE #1598: Presense indicator changed colour
**Describe the bug**
https://github.com/online-go/online-go.com/commit/4a1d9b4d69713300c9c9f86ed57705a97efd615c was supposed to be a non-functional change but accessible.chat-offline was changed from accessible.bg `#1a1a1a` to dark.chat-offline `#cccccc`

@GreenAsJade

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes #1598

## Proposed Changes

 Put back the explicit lines for accessible.chat-offline

### CODE REVIEW

**Comment by GreenAsJade** [comment]
That's irritating - the actual change is just the last commit :D

**Comment by BHydden** [comment]
Still trying to pad those commit numbers I see 😉 25 commits for 1 CSS line, impressive ha ha

**Comment by BHydden** [comment]
Thanks for the quick fix ❤

**Comment by GreenAsJade** [comment]
> Still trying to pad those commit numbers I see 😉 25 commits for 1 CSS line, impressive ha ha

If it really works like that, then I'll get at least double for all those:  PR#1597 

(But I'll be surprised if it does.   If it really does, I'll have to leave my `devel` way behind for longer :D )

**Comment by GreenAsJade** [comment]
> Thanks for the quick fix ❤

I [know how much it meas to you](https://github.com/online-go/online-go.com/blob/660423faa07381af0d4f8cdaa08168abf69309b8/src/ogs.styl#L377-L378)  ;)

**Comment by BHydden** [comment]
haha, yes I did notice that sneaky addition ❤️ though in this instance I noted in mod chat that I was fine with it either way haha, KoBa insisted that the shades were too similar so I went hunting 😉

**Pull request merged**
