### PR TITLE
Vladislav Vinokurov YT link update

### PR DESCRIPTION
**Pull request by BHydden**
Fixes broken link

### CODE REVIEW

**Comment by BHydden** [comment]
Stupid prettier can't decide if it wants links all on one line or broken up 🤣

**Comment by BHydden** [comment]
Probably a line length thing. Price to pay for making edits in mobile browser I suppose 😅

**Comment by anoek** [comment]
Thanks for the mobile edits!

**Comment by BHydden** [comment]
I have no computer right now so it's the best I can offer 😅

**Pull request merged**
