### PR TITLE
Shorten names for tournament/ladder games in game lists

### LINKED ISSUE #2424: Relevant parts of game names not visible for tournaments and ladders in game lists
**Describe the bug**
Game names for tournaments and ladders are long always start with the same prefix. This is the only text visible in game lists, whether active games or lists of previously played games, because the relevant text overflows.

This is borderline between an enhancement and a bugfix. Let me know if you'd prefer a discussion on the forums before proceeding. In any case, I have a patch, and I'll post a pull request in a moment.

### PR DESCRIPTION
**Pull request by dexonsmith**
Show more of the relevant part of the game name in game lists before the text overflows, by replacing:

- the "Tournament Game:" prefix with the trophy icon and
- the "Ladder Challenge:" prefix with the ladder icon.

Without this change, the now-shortened prefix was the only visible text in such games.

This fixes both `GobanLineSummary` and `GameHistoryTable`.

Fixes #2424

### CODE REVIEW

**Comment by dexonsmith** [comment]
BTW, I'm new to React and TypeScript... the initial patch shares the core logic for this change between the two places, but duplicates the rendering code. Not sure if this is okay, or too spaghetti-like.

I had a look at sharing the rendering code but what I came up with (changing the new `GameNameForList` type to a `class` and adding a `render()` function) seemed too heavyweight for such a small use case. Let me know if you want me to look more in that direction.

**Comment by dexonsmith** [comment]
Just pushed d4f047b5f318ed84582845035dc4ffbd9d3db62b to respond to CI failure (I hadn't seen failures locally when testing with beta.online-go.com... looks like the CI checks more thoroughly!).

**Comment by benjaminpjones** [comment]
> I had a look at sharing the rendering code but what I came up with (changing the new `GameNameForList` type to a `class` and adding a `render()` function) seemed too heavyweight for such a small use case.

React has Functional Components that are a lot lighter weight than class components.  In modern React these are preferred anyway ([the React docs](https://react.dev/reference/react/Component) only cover class components as a "Legacy API").

This PR looks good to me as-is, but I've opened https://github.com/dexonsmith/online-go.com/pull/1 as an example of how you can dedupe the render code too.  IMO pretty light-weight or maybe lighter since there is no longer a need for an intermediate object.

**Comment by dexonsmith** [comment]
> This PR looks good to me as-is, but I've opened PR [dexonsmith#1](https://github.com/dexonsmith/online-go.com/pull/1) as an example of how you can dedupe the render code too.

Awesome; your version is what I might have hoped for, so I merged it in.

**Comment by dexonsmith** [comment]
Some screenshots.

Ladders before / after / after with title:
LadderBefore
LadderAfter
LadderTitle

Tournaments before / after / after with title:
TournamentBefore
TournamentAfter
TournamentTitle

**Comment by dexonsmith** [comment]
> This PR looks good to me as-is, but I've opened PR [dexonsmith#1](https://github.com/dexonsmith/online-go.com/pull/1) as an example of how you can dedupe the render code too.

(BTW, if you preferred my patch before your change, I can force push back to that version. But it seems useful to me for the archived games and current games to share the rendering code, in case there are other tweaks to make, and this seems pretty clean.)

**Comment by BHydden** [comment]
Long overdue. Thank you ❤️

**Comment by BHydden** [comment]
I don't know if it's in scope, but could the ladder games say which ladder they belong to? Many ladder players are in multiple ladders and it's hard to tell them apart.

**Comment by dexonsmith** [comment]
> I don't know if it's in scope, but could the ladder games say which ladder they belong to? Many ladder players are in multiple ladders and it's hard to tell them apart.

I think better to do separately (IMO, out of scope). It might also be better server-side... depending on where the logic for creating/naming ladder games (I haven't looked yet).

IMO, it'd be better to actually change the names of the games to include the ladder name, rather than just prettifying it in game lists (which is what this patch does). I.e., the game-creation logic could be changed such that the name is something like:

    Ladder Challenge: Name of Ladder: challenger(#3) vs challenged(#2)

And then this patch would (continue to) prettify the display of the name in game lists to use the ladder symbol instead of the words "Ladder Challenge:".

Unlike this patch, it wouldn't retroactively change names of old ladder games, but new ones would include the ladder name.

**Comment by dexonsmith** [comment]
> I think better to do separately (IMO, out of scope). It might also be better server-side... depending on where the logic for creating/naming ladder games (I haven't looked yet).

Yeah, confirmed the names are generated server-side. This is what online-go.com sends to the server:
```
post(
    `ladders/${this.props.ladder.props.match.params.ladder_id}/players/challenge`,
    {
        player_id: ladder_player.player.id,
    },
)
```
I'd be happy to write a patch for that, but I don't think I have access to the server code right now.

**Pull request merged**
