### PR TITLE
update moderator language flags

### PR DESCRIPTION
**Pull request by RubyMineshaft**
Changed some language flags as requested in https://forums.online-go.com/t/language-skills-of-current-mod-team/39054/

### CODE REVIEW

**Comment by anoek** [comment]
Thanks!

**Comment by BHydden** [comment]
@anoek one of the intents of this pull request was to make Kosh's flag specifically English 🏴󠁧󠁢󠁥󠁮󠁧󠁿 that's why his code was changed to [eng] not [en] like the others. However this has failed and his flag automatically changes to viewers' nation just like [en] does.

[Kosh's request](https://forums.online-go.com/t/language-skills-of-current-mod-team/39054/51?u=bhydden)

**Comment by BHydden** [comment]
Was there an error in how RM implemented it?

**Comment by anoek** [comment]
Ah, yeah I think it should just be "_England" for that

**Comment by anoek** [comment]
like get rid of the getLanguageFlag call, that just tries to guess the right flag for a given languge, if you want a specific flag though, just use the flag string

**Comment by BHydden** [comment]
@RubyMineshaft while you're fixing that up, KoBa and Vsotvep also requested [gb] instead of [en] for their languages

**Comment by RubyMineshaft** [comment]
Oops, just saw this. It was working on my end when I was testing, weird.

**Comment by RubyMineshaft** [comment]
I'm seeing English and gb flags on my end, I'm guessing you guess already fixed this

**Comment by BHydden** [comment]
Since my comments I can now see GB flags for Vsotvep and KoBa on my end, however Kosh is still being interpreted as a regular English flag and being converted to user's country (in my case Australian flag) like all the others, instead of being locked into the flag of England. 

image

**Comment by RubyMineshaft** [comment]
I wonder why it shows me England and changes it to an Australian flag for you. I want to go through the code and try to understand how that works when I have time, but since just changing it to `"_England"` fixes it, great.

**Pull request merged**
