### PR TITLE
Add support for creating groups with admin only tournaments

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes organisations being unable to prevent members creating tournaments

## Proposed Changes

Use the `admin_only_tournaments` field to turn off create tournament buttons for users

** Needs https://github.com/online-go/ogs/pull/1802

### CODE REVIEW

**Comment by anoek** [comment]
I reckon we should probably add that checkbox when editing a group too?

**Comment by GreenAsJade** [comment]
> I reckon we should probably add that checkbox when editing a group too?

I _knew_ I should have done that to start with 😝

**Comment by BHydden** [comment]
What is this secret repo with 1800 pull requests? 😉

**Comment by GreenAsJade** [comment]
That, of course, is the Mystical Back End!

**Comment by BHydden** [comment]
Is it as bad as he says? 😉

**Comment by GreenAsJade** [comment]
Heh did a Lot Of Work to make it a pleasant environment 😅

**Comment by anoek** [comment]
Awesome thanks for the followup :)

**Pull request merged**
