### PR TITLE
Show players flags on game pages

### PR DESCRIPTION
**Pull request by mlopezviedma**

### CODE REVIEW

**Comment by anoek** [comment]
:+1:  but while this didn't cause #128, I  want to hold off on merging this until we fix that too, either in this pr or another

**Comment by mlopezviedma** [comment]
I guess that should do the trick

**Comment by anoek** [comment]
Looking mostly good!

ogs minibeast com-game-7172612 iphone 6 plus

Looks like in squashed mode it's a little funky still?

**Comment by mlopezviedma** [comment]
Oh, squashed. I forgot about that one.

**Comment by anoek** [comment]
Awesome thanks! 

Fixes #128

**Pull request merged**
