### PR TITLE
Various tweaks: alert banner for megaphone, joseki graph, joseki play mode record fix

### PR DESCRIPTION
**Pull request by GreenAsJade**
## Proposed Changes

Show a highlighted banner with official message when megaphone is on.

(Also, more tidyup of Joseki stats graph)

Screen Shot 2020-04-19 at 11 54 05 am

### CODE REVIEW

**Comment by anoek** [comment]
Thanks for the improvements :) Ideally PR's should be a little more separated, one for the joseki improvements, one for the megaphone banner, that kind of thing - but ideally they should also be commented on and merged before 45 days, so I'm just gonna hit merge on this one. Thanks!

**Comment by BHydden** [comment]
how do you feel about my suggestion above that the text should be translation wrapped?

**Comment by anoek** [comment]
I don't see your suggestion, I do see `line.text(_("OGS Moderator official message: please respond"));` so I think it is though, or are you talking about something else?

**Comment by BHydden** [comment]
I started a review, I guess maybe that pending thing makes it invisible? but I'm surprised you can't see it...

image

**Comment by BHydden** [comment]
ohhhhhhhhhhh I see.... he made the changes... and so now I need to go back and say whether it fixed the problem or not lol, thanks sneaky @GreenAsJade for implementing my suggestion without comment :P

**Pull request merged**
