### PR TITLE
Joseki DB Lockdown for Admin, and basic usage visibility (for all), caching.

### PR DESCRIPTION
**Pull request by GreenAsJade**
Provides a "lockdown" button for Admins to press, which puts the thing into a "maintenance mode" where no-one can edit.

Exposes the position visit counter: total, and daily.

*** Needs server 4f26c5af ***

### CODE REVIEW

**Comment by GreenAsJade** [comment]
This should get a run on beta first, I think.

**Comment by GreenAsJade** [comment]
The most recent change introduces caching of fetched joseki positions, addressing #948

**Comment by anoek** [comment]
This is now on beta along with the new joseki server code for your testing

**Comment by GreenAsJade** [comment]
Thanks!   Looks to be working :)

Seems ready for live.

**Comment by anoek** [comment]
Awesome, thanks!

**Pull request merged**
