### PR TITLE
Added prettier-eslint as a dev dependency.

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes: not having prettier-eslint when you need it.

### CODE REVIEW

**Comment by BHydden** [comment]
heh I was wondering if the TS bump was intentional :P

**Comment by GreenAsJade** [comment]
Yeah - for some reason something I did caused something to decide to install that: I'm not sure, what, it wasn't manual or deliberate.   I did actually see it and kind of shrugged.  Moral of the story: don't shrug (4.5.4 brings nasty warnings).

**Comment by BHydden** [comment]
> 4.5.4 brings nasty warnings

from memory ben bumped TS recently to something more feature rich and deliberately chose the last version that didn't break everything :P

**Comment by benjaminpjones** [comment]
>from memory ben bumped TS recently to something more feature rich and deliberately chose the last version that didn't break everything :P

Maybe thinking of sweetalert? https://github.com/online-go/online-go.com/pull/1548

**Comment by anoek** [comment]
There was a bump to the eslint plugin that needed to happen as typescript was bumped, migtha been what he saw. https://github.com/online-go/online-go.com/commit/5a056b74353228382c7ab6670a3ecda16c12c3ef is in as of this morning though, so we're upgraded now, nothing seemed to break.

**Comment by BHydden** [comment]
> Maybe thinking of sweetalert?

haha yeah that was it 😅 not even close lol

**Pull request merged**
