### PR TITLE
Play page rengo layout

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes nothing probably :)

## Proposed Changes

Put live Rengo games before correspondence normal games on Play

### CODE REVIEW

**Comment by GreenAsJade** [comment]
This is a PR so we can let folk play with it, not proposed for Prod yet

**Comment by GreenAsJade** [comment]
Looks like Uffizzi is broken:

[Use Remote Workflow to Preview on Uffizzi / Create, Update, or Delete Preview on Uffizzi](https://github.com/online-go/online-go.com/actions/runs/4451893505/jobs/7819048929#step:10:1)
Unexpected input(s) 'compose-file-cache-key', valid inputs are ['script', 'github-token', 'debug', 'user-agent', 'previews', 'result-encoding', 'retries', 'retry-exempt-status-codes']

**Comment by GreenAsJade** [comment]
Curiously, it has come good 🤷‍♀️

What back-end does Uffizzi point at?

**Comment by BHydden** [comment]
I swear it used to be live 🤔

Doesn't uffizzi lose a lot of its usefulness if it's not pointing at the main server?

**Comment by benjaminpjones** [comment]
> I swear it used to be live 🤔

https://github.com/online-go/online-go.com/commit/f0c2cfa2db28834a3765e3dc3022fcbc2b191daf

**Comment by GreenAsJade** [comment]
I can imagine that the thinking is "if you are trying something out, rather than using it in earnest, then you should not be affecting Prod data"

**Comment by BHydden** [comment]
That's why it makes sense to have both. 
Upload the breaking tests to beta,
Have uffizzi point ar prod for the tests that need real world data that is hard to fake.
Having uffizzi point at the beta server makes it almost redundant. All it does is stop anoek needing to manually push to beta.

**Comment by GreenAsJade** [comment]
No, it means we can independently test on a real server multiple different branches without having to merge them.

**Comment by anoek** [comment]
It was at live, but I switched it to beta a few (days?) ago. I figured that was safer in general.. I thought about making it something you can switch though, both are definitely useful use cases.

**Comment by BHydden** [comment]
> https://makeameme.org/meme/i-always-test
> 
> ;)

OGS thuglife 😎

**Comment by anoek** [comment]
FYI: f0c2cfa2db28834a3765e3dc3022fcbc2b191daf is the commit I changed it to beta, so I think you just need to swap the `OGS_BACKEND` comment in `.github/uffizzi/docker-compose.uffizzi.yml` and you're all set. Feel free to swap it back, I don't have a strong preference.

**Comment by GreenAsJade** [comment]
The real attraction of Prod is definitely-seeing-what-exists-there-in-the-way-it-will-look.

I wonder whether we could just as well have two uffizzis per PR as one?

**Comment by GreenAsJade** [comment]
This is a challenge for another time.

**Pull request closed without merging**
