### PR TITLE
debounce updates in paginated table

### PR DESCRIPTION
**Pull request by flurmbo**
My go at fixing #939. Not sure if this is the best implementation, but it does fix the issue with the wrong page being shown sometimes.

## Proposed Changes

  - remove the blocking `this.updating` class member on the PaginatedTable component
  - remove `this.needs_another_update`
  - debounce calls to update() by 100 ms

### CODE REVIEW

**Comment by GreenAsJade** [comment]
This has needed to be fixed for ages!  Yay!

Is it conceivable to count the "bounces" and actually advance by that much?   I haven't thought about it too much, but it is irritating to know you want to go 5 pages back and have to click to 5 slowly.

There is actually the same problem with the back button in the Joseki Explorer: it goes too slowly because it waits for each update before it lets you click again.

**Comment by BHydden** [comment]
Surely you could implement both with a local count variable that increments and decrements based on requests and updates?

**Comment by GreenAsJade** [comment]
Don't call me Shirley!

**Comment by BHydden** [comment]
Ok, but I am serious ;-)

**Comment by anoek** [comment]
The `updating` / `needs_another_update` pattern code you see in there is solving a different problem - if you're typing numbers / paging through results, sometimes each page takes a long time to load. The updating pattern makes it so if a request is in flight, we don't update until it comes back. If we need to update again when it comes back, we do so then.

The problem with the debounce solution you have is that if someone is paging through results and things are taking awhile (such as looking through games on a bot record, sometimes those take a few seconds to complete even), it's quite possible that it's going to start new requests before the old ones have finished, and then as those requests complete it's going to refresh the page results with the last one completed.

Thanks for the attempt though, and I certainly welcome future attempts at fixing this rather annoying bug!

**Comment by flurmbo** [comment]
Thanks for the explanation @anoek, is the problem you referring to this sort of behavior in the gif below (tested with my changes)? The interval between some requests is greater than the debounce interval, so we see multiple updates in quick succession.

One way I thought of dealing with that is keeping track of the last ajax request made and then after receiving data from server only updating if that data is from the most recent request made. Could be a little complicated and might make UI a bit unresponsive though

ogs

**Comment by BHydden** [comment]
What if you added a half second wait after each number edit was pressed before the request is sent? That gives you time to enter the full desired number and it can shoot off a single request

**Pull request closed without merging**
