### PR TITLE
hide private-chat in zen mode

### PR DESCRIPTION
**Pull request by flovo**
In the forum it was mentioned that the private-chat window is disturbing the zen experience (minimal disturbance). 

https://forums.online-go.com/t/hide-messages-while-being-in-zen-mode/23026

This should hide the private-chat window while Zen mode is active. 
Hopefully superchat still shows up. (If I interpret it correctly superchat means a moderator wants to talk to you officially). Obviously I haven't tested if moderator chat is still visible.

### CODE REVIEW

**Comment by BHydden** [comment]
want me to hop on beta server and pm you to test?

**Comment by flovo** [comment]
Yes, lets do a quick test.

**Comment by flovo** [comment]
Superchat should work now.

**Comment by anoek** [comment]
Nice, thanks!

**Pull request merged**
