### PR TITLE
Added confirm dialog for undo button

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes [accidentally asking for undo](https://forums.online-go.com/t/feature-request-cancel-undo-request/48099?u=greenasjade)

## Proposed Changes

Have a confirm dialog for undo.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Note: there's some discussion in the forum about whether this is a Good Thing (TM) and whether it needs to be tweaked.

Draft for now.

**Comment by anoek** [comment]
Hmm, maybe we put this behind an setting? I haven't heard this being a particularly notable problem in the past, so I think we might get some more push-back from having it defaulting a prompt whenever undo is clicked.

**Comment by GreenAsJade** [comment]
The suggestion in the forum is that if you have submit for click then you get this dialog as well.

I dunno, I suspect that the real answer is going to be to provide "cancel undo request", which is kind much more hassle :)

**Comment by anoek** [comment]
Yeah agreed on both accounts.

**Comment by anoek** [comment]
FWIW I do think cancel undo request is feasible

**Comment by anoek** [comment]
Misclick on the close, sorry - I do think the cancel undo request is feasible fwiw, I don't think there would be any major blockers, just takes tracing that through all the different layers. It'd definitely be a good thing to have though, I should have implemented that right away when I did undo.

I think this is probably going to be useful even when we finally get around to undo-undo though so :+1:  once we get it behind a check for submit-to-move

**Comment by BHydden** [comment]
> Misclick on the close, sorry

The irony is just so delicious ❤️

**Comment by GreenAsJade** [comment]
Yeah cancel-undo should be readily doable, just not in the "oh, I'll wack that out right now" bucket :)

**Comment by BHydden** [comment]
Can we implement the confirm dialog until GaJ is ready to code up the cancel button?

**Pull request closed without merging**
