### PR TITLE
Respect dark mode settings for the profanity filter setting.

### LINKED ISSUE #1278: The new profanity filter does not obey dark-mode setting.
**Describe the bug**
The new profanity filter (#1271) does not obey dark-mode setting.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by benjaminpjones**
Fixes #1278 

Screen Shot 2020-11-21 at 12 15 50 AM

### CODE REVIEW

**Comment by mmartin** [comment]
Hover effect does not work properly:
image

Regular drop-downs:
image

**Comment by benjaminpjones** [comment]
@mmartin whew that one was quite a bit harder to figure out.  Not sure why the style settings for the single don't work for the multi.

**Comment by mmartin** [comment]
Also filter text has incorrect color.
image

**Comment by benjaminpjones** [comment]
...anddd we inadvertently fixed the joseki dictionary:

Screen Shot 2020-11-21 at 2 05 13 AM

Thanks for digging into this @mmartin. Dark mode was way of my radar, but I am glad someone is looking into my stuff!

**Comment by BHydden** [comment]
> Dark mode was way off my radar, but I am glad someone is looking into my stuff!

The simple fix for this is to upgrade to the vastly superior "dark mode" as your daily user experience :wink:

**Comment by anoek** [comment]
Thanks for the quick fix, and thanks @mmartin for checking this out before it hit production!

**Pull request merged**
