### PR TITLE
Set game thumbnails list threshold on Observe page

### PR DESCRIPTION
**Pull request by mlopezviedma**
Implements #262.

### CODE REVIEW

**Comment by anoek** [comment]
Hmm, not sure I'm a fan of how this affects the balance of the page. I kinda question how used the original feature request would be to begin with too, there hasn't been any comments on it.

**Comment by mlopezviedma** [comment]
You mean the position and the space it takes?

**Comment by anoek** [comment]
Yeah, without some confirmation that this is a widely desired feature, I don't think we should implement this in such a prominent wau (and perhaps not at all)

**Comment by mlopezviedma** [comment]
Yeah, I pretty much agree with you. Let's see what everyone thinks :)

**Comment by apetresc** [comment]
Personally, I like this change, just because it's such a standard UI thing in most web applications with pagination to set the page size directly from the interface its modifying. (Though I haven't actually pulled @mlopezviedma's patch yet to see how this particular implementation looks)

**Comment by anoek** [comment]
The effect here is two pagination sizes though, which I think is confusing.

I was thinking about it more, I think that's my primary complaint. We might consider decoupling this list from that limit, and instead just have a toggle on the watch page that toggles from list to thumbnails, and completely ignore that size setting. Then it can be just a simple single icon instead of a big list, which would fit a lot better I think. What do you guys think?

**Comment by mlopezviedma** [comment]
I like that a lot! Furthermore, list threshold is also applied to profile pages, so changing this preference in other place than **Settings** looks somewhat inconsistent to me.

**Comment by anoek** [comment]
Closing this in favor of waiting for a patch that does the thumbnail/list toggle button instead

**Pull request closed without merging**
