### PR TITLE
Adding filters to challange list

### PR DESCRIPTION
**Pull request by flovo**
Allow the users to filter the challenge list for some game properties. 

This is related to #1062 

## Proposed Changes

New filter options
  - only ranked / unranked
  - 19x19, 13x13, 9x9, other board sizes

screenshot of the options

### CODE REVIEW

**Comment by BHydden** [comment]
I have no idea why I didn't think of this!! great work <3

**Comment by anoek** [comment]
Nice, thanks!

**Comment by mlopezviedma** [comment]
Could this also allow filtering by handicap and rules?

**Comment by flovo** [comment]
You can filter everything column.

**Pull request merged**
