### PR TITLE
OJE Throbber Spinner Light theme and Go Resources IGA

### PR DESCRIPTION
**Pull request by shinuito**
## Fixes 
In light theme while the OJE, joseki explorer is loading the throbber spinner is white like the background, hence is invisible, unlike in dark theme. Changed the background of spinner to use themed(background,shade0), which at least has some contrast to the theme background.

## Proposed Changes

  - Add a link to the Irish Go Association in the Other Go resources page, with Ireland flag beside the link.

### Comment/Question

I'm not sure why the yarn version is different from the main repository in package.json and yarn.lock. I'm using npm 6.14.14, node.js v14.17.5 . Is there another version I should use instead? The cache loader line just seems to have been moved automatically (alphabetically), but not changed.

### CODE REVIEW

**Comment by anoek** [comment]
Thanks for the fix and the addition!

**Comment by GreenAsJade** [comment]
@anoek  What was the deal with the changes to yarn.lock?   I saw you committed them ... curious what causes that to happen?

**Comment by anoek** [comment]
Looks like just a version bump for yarn itself, pretty benign.

**Comment by GreenAsJade** [comment]
Cool

**Pull request merged**
