### PR TITLE
Player notes on friends list

### PR DESCRIPTION
**Pull request by GreenAsJade**
Adds an indicator of player notes presence on the friends list.

The little icon is clickable to open the PlayerNotesModal.

(building on the work of previous PRs)

Screen Shot 2021-04-15 at 9 28 48 pm

### CODE REVIEW

**Comment by anoek** [comment]
I'm wondering if we should put that indicator code in the Player component, that way we can turn it on/off anywhere where we use that? Might be good to have it default on so it's just kinda everywhere.

If we go that route, I'm not sure we should put a full note pad icon near the name though, maybe either an indicator dot or a color change or something?

**Comment by BHydden** [comment]
I disagree... I think the clipboard icon does a good job of representing notes... certainly a dot should not be used as it would be confused with the online presence indicator

**Comment by GreenAsJade** [comment]
Doh - definitely it should be in the Player component.  As BHydden, I do like the notepad: in the absence of that, it takes a fair bit of "intuition" to work out why the name is bold (or whatever).

**Comment by anoek** [comment]
Sounds good, notes icon it is.

**Comment by GreenAsJade** [comment]
This now has the latest remote-storage, being called explicitly as needed.

It's a lot more work to make something pre-existing use remote-storage now : you have to find all the places it was referenced.  But that may not be a bad thing, because it makes you think about what if this thing changes unexpectedly in each of those places.

This doesn't have player note icon extracted into Player ... separate branch for that, I'm not totally wild about the result.

**Pull request closed without merging**
