### PR TITLE
Prevent click events in player popover from reaching game history table

### LINKED ISSUE #2109: Random game opens when trying to navigate someones profile via game history
**Describe the bug**
When i go to game history on someones profile, click their opponents name twice in order to get to that oppos profile, a random game of the first player opens. 

**To Reproduce**
1. Go to any users profile
2. scrolld down  till you reach game history and click on their opponents name
3. click again their name
4. game that you didnt click opens

**Expected behavior**
Have the opponents profile open

**Screenshots**

https://user-images.githubusercontent.com/29932807/211588365-21129b1a-ca64-4b92-acf1-6ebf717cec52.mp4

### PR DESCRIPTION
**Pull request by turtoise0**
Fixes #2109, replaces #2141

## Proposed Changes

Handle click event instead of mouse down in `Player`.

Previously, the game history table was being clicked instead of the player link because `Player` was handling mouse down events while the PaginatedTable row was handling mouse ups.

Also removes some code that's no longer needed.

### CODE REVIEW

**Comment by BHydden** [comment]
Are you sure the extra code you removed didn't re-break #1003 and #1019 ?

I'm on a phone so I can't test it myself.

**Comment by turtoise0** [comment]
Like this?

https://user-images.githubusercontent.com/99894371/217695678-7c93697c-7ac2-4e80-9321-be69024774bd.mp4

It still works on desktop chrome and firefox.

**Comment by BHydden** [comment]
Looks good! Great choice of profile too 😉

**Comment by anoek** [comment]
Awesome, thanks for hunting that down and getting it fixed!

I have no recollection of why we used `onMouseDown` instead of `onClick`. It might have been an old workaround, or just plain silliness, regardless `onClick` seems to work great in all my testing so thanks!

**Pull request merged**
