### PR TITLE
Dockerfile - update base image tag

### PR DESCRIPTION
**Pull request by ScottBrenner**
## Proposed Changes
Proposing update the base image tag here to `10.15.1`, following the version used in https://github.com/online-go/online-go.com/blob/devel/shippable.yml#L4

Reference - https://hub.docker.com/layers/node/library/node/10.15.1/images/sha256-8fc2110c6978657838569afd5e135ab2e0b4a668cbd6d56bd963ecea19b03cfd?context=explore

### CODE REVIEW

**Comment by ScottBrenner** [comment]
@hloeffler Mind reviewing?

**Comment by flovo** [comment]
anoek is a little busy right now with [this](https://forums.online-go.com/t/re-correspondence-games-lost-by-disconnection/26703/261?u=flovo) but once that's resolved he should have more time to get back to github issues and PRs

**Comment by hloeffler** [comment]
LGTM, but i cant merge.

**Comment by anoek** [comment]
Thanks for this :) I suppose we should probably bump and test on the latest node too, I didn't realize it had gotten so far behind. I don't expect there should be any issues, I regularly build with node 14.3 these days.

Regardless, I'm merging this for the time being. Thanks for the PR!

**Pull request merged**
