### PR TITLE
Dockerize Development Environment

### PR DESCRIPTION
**Pull request by ScottBrenner**
## Proposed Changes

Moving the development environment into a Docker container and running it with `docker-compose`.

WIP as I'm not terribly familiar with the development environment here and I'm running Docker on Windows which is a bit different, but it "should work" ™️:
```
$ docker-compose up
Building online-go
Step 1/8 : FROM node:10.15.1
...
Successfully tagged online-go:latest
Creating online-go ... done
Attaching to online-go
online-go    | 
online-go    | > online-go.com@5.1.0 dev /usr/src/app
online-go    | > supervisor -w Gulpfile.js,webpack.config.js,tsconfig.json supervisor -w Gulpfile.js -x gulp --
online-go    |
online-go    |
online-go    | Running node-supervisor with
online-go    |   program ''
online-go    |   --watch 'Gulpfile.js'
online-go    |   --extensions 'node,js'
online-go    |   --exec 'gulp'
online-go    |
online-go    | Starting child process with 'gulp '
online-go    | Watching directory '/usr/src/app/Gulpfile.js' for changes.
online-go    | Press rs for restarting the process.
online-go    | [16:54:58] Using gulpfile /usr/src/app/Gulpfile.js
online-go    | [16:54:58] Starting 'default'...
online-go    | [16:54:58] Starting 'dev-server'...
online-go    | [16:54:58] Starting 'livereload-server'...
online-go    | [16:54:58] Starting 'background_webpack'...
online-go    | [16:54:58] Starting 'build_styl'...
online-go    | [16:54:58] Starting 'watch_styl'...
online-go    | [16:54:58] Starting 'watch_dist_js'...
online-go    | [16:54:58] Starting 'watch_html'...
online-go    | [16:54:58] Starting 'watch_tslint'...
online-go    | [16:54:58] Finished 'dev-server' after 80 ms
online-go    | [16:54:58] Finished 'livereload-server' after 81 ms
online-go    | [16:54:58] Finished 'background_webpack' after 87 ms
online-go    | [16:54:58] Finished 'watch_styl' after 133 ms
online-go    | [16:54:58] Finished 'watch_dist_js' after 135 ms
online-go    | [16:54:58] Finished 'watch_html' after 140 ms
online-go    | [16:54:58] Finished 'watch_tslint' after 142 ms
online-go    | #############################################
online-go    | ## Development server started on port 8080 ##
online-go    | ##   http://dev.beta.online-go.com:8080    ##
online-go    | #############################################
online-go    | 
online-go    | > online-go.com@5.1.0 webpack-watch /usr/src/app
online-go    | > webpack --watch --progress --colors
online-go    |
online-go    | <s> [webpack.Progress] 0% compiling
...
```
Result:
image

_closes #1162_

### CODE REVIEW

**Comment by anoek** [comment]
I'd be happy to have a docker dev environment *option* but please don't replace the existing instructions and make targets.

**Comment by ScottBrenner** [comment]
Sure, https://github.com/online-go/online-go.com/pull/1161/commits/c15d007d89e22560919365b8a7c01a87cd2f6720

**Comment by anoek** [comment]
Awesome, thanks!

**Comment by GreenAsJade** [comment]
Great initiative!

**Comment by ScottBrenner** [comment]
Can anyone confirm that this actually works? Didn't get past the loading screen in my computer.

**Pull request merged**
