### PR TITLE
fixes #908 Joseki filter crash - GreenAsJade to test and confirm

### LINKED ISSUE #908: Joseki filter crash
**Describe the bug**
Setting Filter by Tag to top option "" crashes the site

**To Reproduce**
1. Go to Joseki -> Explore -> Filter
2. Select the top option "" from Filter by Tag
3. See that the site crashes

**Expected behavior**
Fields should reset to default

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Browser Chrome
 - Version 77.0.3865.73

**Additional context**
```
Congratulations, you found a bug!
Our team has been notified of the bug, however if you have more details you'd like to provide, please click here to fill out a report.
Cannot read property 'sort' of undefined

    in zo
    in t
    in t
    in U
    in div
    in Unknown
    in t
```

### PR DESCRIPTION
**Pull request by BHydden**
Fixes #908 

## Proposed Changes

  - Remove the line that adds an empty element to the start

Co-authored-by: @GreenAsJade

### CODE REVIEW

**Comment by BHydden** [comment]
hmm @GreenAsJade my co-author tag didn't work :( I guess I need to know your GitHub email?

**Comment by BHydden** [comment]
hahaha ok cool so you get co-author credit for that one commit but not the whole PR that makes sense 😛

**Comment by GreenAsJade** [comment]
Confirmed: this works.

**Comment by anoek** [comment]
Thanks!

**Pull request merged**
