### PR TITLE
Windows dev detailed steps

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes Windows developers struggling to get started.

## Proposed Changes

Add a tried / tested detailed process for getting development environment up on Windows.

### CODE REVIEW

**Comment by anoek** [comment]
Nice, thanks!

**Comment by BHydden** [comment]
1. Install linux on virtual machine
2. ...
3. Profit.

**Comment by benjaminpjones** [comment]
VM is no longer necessary - I hear WSL is pretty decent!

**Comment by BHydden** [comment]
I think I would still prefer a clean dev environment 🤔

**Comment by GreenAsJade** [comment]
.... _NOW_ everyone comes out with alternatives for helping Windows people ;) 😝

I was more expecting this review to bail me up about the choice of crlf handling.    I'm not sure if that is wise advice or not, it just WFM.  😆

And, in all seriousness, I think that if there's an option that doesn't invoke "Bah, you unix people are just trying to force me to use unix", then that's probably a good thing.

Also, I'm serious when I typed that t"hese instructions seem helpful for a unix person", especially a person new to most of the toolchain.

nvm for installing node was painless - I think windows and unix - and VSCode has surprisingly good git support (which I didn't know before because I use SmartGit).

I don't recall my own getting-started on linux working these things out along the way being as smooth as following that procedure for windows.

**Comment by BHydden** [comment]
I didn't notice people had reported it being an issue. I remember I tried at first, and it was a huge headache, so before the end of the first day I picked the low hanging fruit of setting up a linux VM dev environment haha

**Pull request merged**
