### PR TITLE
Remove max container width

### PR DESCRIPTION
**Pull request by BHydden**
Fixes pages not filling screen with content

https://forums.online-go.com/t/wish-layout-of-watch-page-similar-to-home-page/48139/7?u=bhydden

### CODE REVIEW

**Comment by BHydden** [comment]
Looks ok on my mobile but should be checked on a bigger monitor.

**Comment by GreenAsJade** [comment]
I think this needs some work for wider screens - the items at the top are all kinda far-flung and "lost looking":

Screenshot 2023-06-02 at 4 35 00 pm (2)

Screenshot 2023-06-02 at 4 39 55 pm (2)

**Comment by BHydden** [comment]
Hmm 🤔 thanks for the feedback. It does look a bit haphazard. 
Maybe if I pinned refresh to the left edge of show boards box on the top right rather than having it in centre, would that help? It's the best I can think of since I don't think we want to make those buttons big enough to fill the screen.

**Comment by BHydden** [comment]
As for the No games being played advisory... I think that can stay centred.

**Pull request closed without merging**
