### PR TITLE
Redo player container gradients based on forum feedback

### LINKED ISSUE #1014: Moderator names very hard to read in dark mode white player container
**Describe the bug**

Purple Moderator names very hard to read in the new dark mode white player container colour scheme

**To Reproduce**

Challenge a moderator to a game where they play white.   When they accept, set dark mode and look at their name on the game page.

Or view here:  https://online-go.com/game/20715145   :)

I forgot this variation when testing that new colour scheme!

I guess pros are another ... what other variations of what can appear in the container are there, I wonder?

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes #1014, #1015

## Proposed Changes

Redo gradients based on feedback [here](https://forums.online-go.com/t/bot-name-gone-from-white-player-box/23991?u=eugene)

Now dark mode looks like this with various types of white player:

Screen Shot 2019-12-10 at 9 57 03 pm (2)
Screen Shot 2019-12-10 at 8 46 40 pm (2)
Screen Shot 2019-12-10 at 9 49 26 pm (2)
Screen Shot 2019-12-10 at 9 49 30 pm (2)

### CODE REVIEW

**Comment by BHydden** [comment]
Looks slick. Loving it!

**Comment by anoek** [comment]
Nice :)

**Comment by GreenAsJade** [comment]
Note that this might not be the final best solution, but it's an important and urgent bugfix for Bot names showing up, and seems passable for a step in the right direction.

**Comment by BHydden** [comment]
Don't let the heretics sway you from your path

**Pull request merged**
