### PR TITLE
Make it so you can't have pause on weekend with Simple time.

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes games hanging because the clock stops ticking forever in Simple time games that have pause on weekends set.

## Proposed Changes

Disable the setting of pause on weekends for Simple time.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Note: this has become important because currently any rengo casual mode game with simple time and pause on weekend is pretty doomed to get stuck when one of the players decides to stop playing.

eg https://online-go.com/game/40362506

(It ended up in this state because " a moderator" started it, which converted it to Simple time ... but it had the pause on weekend flag set, and this stayed that way.)

**Comment by anoek** [comment]
Oye, yeah we should probably fix that bug so it doesn't happen in the first place. I'm going to leave this open as a nag for either of us to evaluate the difficulty of fixing the simple timer resetting after weekend (or I think any pause?). It might not even be that bad to fix.

**Comment by GreenAsJade** [comment]
I do have it on my "todo list".  I think it'd be worth pushing this into prod though, because otherwise we are likely to end up with more games where there is no way to rescue them...

**Comment by GreenAsJade** [comment]
... interestingly it's hard to guard against, because as far as I can see, a moderator can't tell if an active challenge is pause on weekends or not!

**Comment by anoek** [comment]
OK I think I found and fixed the issue with simple time, obviating the need for this patch. Here's to hoping I don't screw up more than 1,000 with the fix. :crossed_fingers:

**Comment by GreenAsJade** [comment]
🎉  🎉  🎉   🤞  🤞

**Pull request closed without merging**
