### PR TITLE
Templates

### PR DESCRIPTION
**Pull request by RubyMineshaft**
Added three new warning templates. Feel free to adjust the wording if needed.

### CODE REVIEW

**Comment by RubyMineshaft** [comment]
I'm not sure what I did wrong here.

**Comment by BHydden** [comment]
Nothing I don't think... my guess is it just needs to run again. It just had trouble initialising node from what I can see.

**Comment by BHydden** [comment]
CI/build passed... that's the OGS test... the one that failed was for ufizzi preview

**Comment by anoek** [comment]
Thanks!

**Pull request merged**
