### PR TITLE
Give mods a button to copy a PM session to the player's moderator log

### PR DESCRIPTION
**Pull request by GreenAsJade**
It's mildly a nuisance to copy and paste the dialog with players into their moderator log.

Here is a button that does it in one click.

### CODE REVIEW

**Comment by BHydden** [comment]
Honestly, I could see myself misclicking this far too often, especially since we have  no way to delete mod logs... I can't say I'm realy in favour of this... plus there are all the times you don't necessarily want the whole chat history, if you've spoken with them about unrelated matters prior.

**Comment by GreenAsJade** [comment]
It could have a confirm button, though mod logs are cheap.

If you don't want the whole lot, maybe copy and paste as normal...

**Comment by BHydden** [comment]
Mod logs aren't cheap, they're permanent. They're one of the few things on the site we can't correct. My issue is not at all "I wouldn't use it" my issue is gravely and severely "I might unintentionally use it with no means of correction"

**Comment by GreenAsJade** [comment]
Mmm - maybe we do need a delete-mod-log button.

**Comment by BHydden** [comment]
> Mmm - maybe we do need a delete-mod-log button.

This would have my undying support ❤️ if we had that, I would have no issues at all with your current PR :-)

**Comment by GreenAsJade** [comment]
But ... since that's probably API dependent - what if we had a confirmation dialog where you could edit what's going into the log if you want?

**Comment by BHydden** [comment]
Yeah that sounds pretty good actually, I'd probably use that

**Comment by GreenAsJade** [comment]
OK, that was a good improvement, I like it.

**Comment by GreenAsJade** [comment]
Screen Shot 2020-05-08 at 6 37 49 pm (2)

**Comment by BHydden** [comment]
> Cease thy trolling!

Never!!! 🤣

**Comment by anoek** [comment]
Looks great, thanks!

**Pull request merged**
