### PR TITLE
PM Reporting

### LINKED ISSUE #1507: Ability to report private messages
It would be great to have a report button in the PM window that provides moderators access to the conversation being reported.  

We currently have to rely on players to copy and paste the conversation or provide a screenshot, which opens the possibility of the reporter spoofing parts of the conversation or removing things.

### PR DESCRIPTION
**Pull request by RubyMineshaft**
Fixes #1507

## Proposed Changes

- I've added a report button to the top of the pm window
Screen Shot 2021-08-03 at 11 16 03 PM

- Clicking the report button will open this report modal (There's a typo in "moderation" in this screenshot, but it's been corrected)
Screen Shot 2021-08-03 at 10 54 43 PM

- PM reports will include a link to View Reported Conversation
Screen Shot 2021-08-03 at 10 55 03 PM

- Which in turn opens a modal containing the chat
Screen Shot 2021-08-03 at 10 55 13 PM
Screen Shot 2021-08-03 at 10 55 29 PM

### CODE REVIEW

**Comment by anoek** [comment]
That was fast, nice job!

**Comment by GreenAsJade** [comment]
I wonder why you would not be able to do this for a moderator?

Up till now we have allowed reporting of moderators, and have investigated those reports diligently...

**Comment by BHydden** [comment]
I assumed that meant moderators couldn't use the button (since we already have a make note from message button) rather than moderators couldn't be reported... But I'll admit i didn't actually look at how the code was implemented.

**Comment by RubyMineshaft** [comment]
> I assumed that meant moderators couldn't use the button (since we already have a make note from message button) rather than moderators couldn't be reported... But I'll admit i didn't actually look at how the code was implemented.

This.  Sorry, I should have written that a bit more clearly.  I just took the button off of the moderators' side because the buttons were too crowded and we don't really need it.

**Pull request merged**
