### PR TITLE
Moderator pm banner

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes people not realising they are getting PMed by a Moderator

## Proposed Changes
Put a banner at the top of the PM box saying it's a moderator

Screen Shot 2020-04-17 at 1 25 32 pm (2)

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Ah woops branched from my own head of Devel.

**Comment by BHydden** [comment]
Nice one! I like it

**Comment by anoek** [comment]
Nice :) And I just had the horrible realization that that entire private chat system is still in jquery.. ooph.

**Comment by BHydden** [comment]
Nothing quite like the joy of discovering code your wrote a decade ago 😅

**Pull request merged**
