### PR TITLE
React18 notification click algorithm update

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes people wanting to get to the most urgent game

## Proposed Changes

        // If we are looking at a board with our move, we want to chose the next lowest-expiration board
        // from the one we chose last time.

        // If we're not looking at a board with move of ours, and we have a move to play, then we want to chose the
        // most urgent move to jump to.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
Pushed this up now to see if you hate any of the tidyups.

**Comment by GreenAsJade** [comment]
(I'm not sure why this build fails - it works locally, I can't see why it doesn't like Goban there: is it a react version thing?)

**Comment by GreenAsJade** [comment]
This seems to basically work in react18 branch.   I haven't gone nuts on corner case testing till it gets a look over.

**Comment by GreenAsJade** [comment]
Requires https://github.com/online-go/ogs-node/pull/14

**Comment by anoek** [comment]
It tends to work better to commit to one branch, then merge that branch into another, as opposed to committing the same changes into two branches and trying to merge them - so that's what I've done here, I reverted the notification manager commit into react18, merged devel into react 18, and so at this point I **think** we're in a good state with this and this PR can be closed? If there were any other changes that happened that were react18 specific though, then those haven't made it in and we'll want to patch for those

**Comment by GreenAsJade** [comment]
Yeah, I typically would have done that, but I was expecting the branches to diverge for react and devel.

**Pull request closed without merging**
