### PR TITLE
Allow CMs to cancel their own reports

### PR DESCRIPTION
**Pull request by LForchini**
## Proposed Changes

  - Allows community moderators to cancel their own reports in the report view

I still have to test and style the changes

### CODE REVIEW

**Comment by LForchini** [comment]
I've styled the action buttons somewhat. The red button doesn't appear unless the report was created by the user; should I disable it instead of hiding it?
 
sc

**Comment by GreenAsJade** [comment]
I prefer it to be hidden in this instance, if the report does not belong to the user, because "does not belong to the user" is by far the prevalent case, so it's clutter to have a disabled button hanging around.

There's no confirmation dialog on a normal user's "Cancel" report function, so I guess that applies here too.   I imagine the thinking is that it's not a lot lost if it's an accident :)

I have a feeling that we should be calling this "Cancel", because the intent is that this is the same functionality as the "Cancel" button that normal users have.   The result of pressing that Cancel button is that the report is set to the closed state _and_ has an annotation "closed by user".

I have an urge to move the button up underneath the reporting user's name.   I can't quite say why, other than it "feels more like the normal user case", and also emphasises that the reason it's here is because this is the reporting user's report.

It could be on the same row as "Actions"?

**Comment by LForchini** [comment]
> I prefer the button to be hidden if the report does not belong to the user, because "the report does not belong to the user" is by far the prevalent case, so it's clutter to have a disabled button hanging around :)

I was thinking the same, so that's the current behavior.

> I have an urge to move the button up underneath the reporting user's name. I can't quite say why, other than it "feels more like the normal user case", and also emphasises that the reason it's here is because this is the reporting user's report.
> 
> It could be on the same row as "Actions"?

I personally prefer an interactivity area over scattering buttons all over the UI :sweat_smile:

**Comment by anoek** [comment]
Thanks!

**Pull request merged**
