### PR TITLE
Fix team page display bug

### PR DESCRIPTION
**Pull request by BHydden**
Adjusted row width for mod names to fix issue #822

### CODE REVIEW

**Comment by BHydden** [comment]
well this obviously borked... the changes are missing despite my commit... give me a moment to figure out why

**Comment by BHydden** [comment]
lol forgot to push my bad seems to be fixed now :)

**Comment by BHydden** [comment]
Hold off on merge I want to add some more polish for mobile view consistency

**Comment by BHydden** [comment]
ok should be good to merge now

**Comment by BHydden** [comment]
I adjusted the width of both moderator and developers so that they would line up when stacked vertically (such as in mobile view)

**Comment by anoek** [comment]
Cool thanks :)

**Pull request merged**
