### PR TITLE
Issue #1449: Span elements to button

### PR DESCRIPTION
**Pull request by krystofffff**
Span elements to button

### CODE REVIEW

**Comment by GreenAsJade** [comment]
I think something is up with the build system.  Last time I had one looking like this it went away when I pushed an update!

**Comment by anoek** [comment]
Yeah it looks like the node build containers switched to v20 and one of our libraries had a dependency issue with that. It's fixed on devel now.

**Comment by anoek** [comment]
Thanks for the patch!

**Comment by benjaminpjones** [comment]
It sounds like this changed the layout - may need to update the css/styl files as well.

See: https://forums.online-go.com/t/ui-broke-scroll-bar-time-control-display/47787?u=benjito

**Pull request merged**
