### PR TITLE
Fix timecop notification

### PR DESCRIPTION
**Pull request by turtoise0**
Fixes the time in the notification when you're about to timeout.

### CODE REVIEW

**Comment by anoek** [comment]
Are we seeing `notification.expiration` in both seconds and milliseconds?

**Comment by turtoise0** [comment]
I think it's in milliseconds, but I wasn't sure.

**Comment by anoek** [comment]
Do you happen to recall what kind of clock was being used in the game(s) you saw the problem in? I think I want to fix the underlying bug rather than do the guessing in this patch, otherwise the mobile devs are probably going to be even more frustrated with me :sweat_smile:

**Comment by turtoise0** [comment]
I was looking at https://beta.online-go.com/game/12170 and https://beta.online-go.com/game/12161.

**Comment by anoek** [comment]
Looks like this has been broken for a *long* time, I think we broke it with  https://github.com/online-go/online-go.com/pull/287 

I reverted that and it looks like it's fixed up, I'm going to close this in favor of that revert to avoid confusion about needing to determine if expiration is in ms/s, it's always in ms

**Pull request closed without merging**
