### PR TITLE
GameHistory: Click on a row opens the game

### PR DESCRIPTION
**Pull request by flovo**
At the moment, only clicking on the game title opens the game. Clicking on any other part in the history does nothing.

With this change a click anywhere in the game history brings you to the respective game.

### CODE REVIEW

**Comment by benjaminpjones** [comment]
This works really nicely!  It feels much needed now that the game name has been de-emphasized.

For consistency's sake, it might make sense to have the **Reviews & Demos** function similarly.

**Comment by BHydden** [comment]
Does the opponent's name still open their context menu? or did it get amalgamated into the giant game link?

**Comment by benjaminpjones** [comment]
@BHydden clicking the opponents name still opens the player card as before.

**Comment by flovo** [comment]
Good catch. Now the reviews and demos table also allows clicking anywhere on the row to open the goban.

**Comment by BHydden** [comment]
Does this make all the columns format to hyperlink blue rather than text grey?

image

**Comment by flovo** [comment]
No. The opposite. The game titles aren't blue anymore.

**Comment by BHydden** [comment]
I wasn't strongly attached to any of the options, but I think this was my preferred one too 🙂

**Comment by anoek** [comment]
This is great, thanks @flovo !

**Pull request merged**
