### PR TITLE
Add server time display

### PR DESCRIPTION
**Pull request by BHydden**
Display current server time above active games on profile page as per [Issue #849](https://github.com/online-go/online-go.com/issues/849)

### CODE REVIEW

**Comment by BHydden** [comment]
@anoek if you like the look of this I'll begin work on implementing it on the /overview page as well and add in a "weekend starts in x hours / end in x hours" for Friday and Sunday but I wanted to get your feedback on what I've done so far.

**Comment by BHydden** [comment]
I believe this version to be functional and stable and could be merged now if you like what you see, as the additional changes I'm thinking of making are, I believe, QoL feature upgrades and not something to hold back deployment if you like what I've done so far...

But by all means, if you have feedback on optimal wording / location / formatting for the server time display I'm all ears 😄

**Comment by BHydden** [comment]
Currently looks like:
image

**Comment by BHydden** [comment]
@anoek with the latest changes I now think this covers everything I wanted it to be, and everything I interpreted was desired from the initial forum thread. Please let me know if you have any recommendations, requests, or ideas for improvement. Otherwise, I think it's good to go. 😄

**Comment by anoek** [comment]
I like that you implemented that as a component, good job :) I'm not convinced that's the best place for that information to live, but it should be pretty easy to move if we figure out a better place for it because you did that.

The primary issue I see is that the strings need to be translatable, see usages of `_` and `interpolate`.

**Comment by BHydden** [comment]
Regarding location, I just tried to put it as close to where players would be looking at their own games as possible, which to me seems like the main time you would be concerned about weekend presence, but as you say it's easy to move anywhere we want.

Hmm ok... I've not done any research into that yet but I'll see how I go... how deep does that need to go? Do the numbers get translated into Asian numbers? Would the day of the week need to be translatable? ...or is it just the preamble at the start that you want to be translatable?

**Comment by anoek** [comment]
`moment` will with translating times into the various formats and localizing the day names and whatnot. This has two implications: (1) you don't need to worry about translating that part, but (2) `this.state.time.startsWith("Saturday")` doesn't work, you should probably just change that to `new Date().getUTCDay() == 6` (6 for Saturday, 0 for Sunday, 5 for Friday)

You can see some examples of `interpolate` and `_` in https://github.com/online-go/online-go.com/blob/devel/src/views/Supporter/PrettyTransactionInfo.tsx#L57 for the rest of the string translations

**Comment by BHydden** [comment]
I wasn't sure if it would update properly if it wasn't attached to this.state.time I was trying to avoid the case where a user has their browser open all the time and the second half of the message never updates... is that an invalid concern born from my ignorance of the finer details of the language?

**Comment by BHydden** [comment]
Does that look right to you? 😄

**Comment by anoek** [comment]
Looking pretty good I think, might want to change the moment format from `dddd, HH:mm:ss` to `dddd LT` though just so the time is presented nicely dependent on locale

**Comment by BHydden** [comment]
*sigh* 😄 I'm more of an ISO guy myself, but I suppose localisation makes the most sense in this context... roger wilco 👍

**Comment by BHydden** [comment]
@anoek for some reason GitHub didn't kick off the auto-checks with that last push?

**Comment by anoek** [comment]
Thanks for the PR BHydden!

**Pull request merged**
