### PR TITLE
Chat improvements

### PR DESCRIPTION
**Pull request by flovo**
Now the chat recognises when an username is followed by a `,` or a `'` as a mention of username.
If the user is mentioned as `player 1`, now this is a mentioning as well.

I also made the space between `player` and the player_id optional. 
Same for `issue` and `pr`.

This still leaves some mentions undetected:
In German `Adam's` would be `Adams` (without Apostrophe). I don't know if there is any language which adds letters at the beginning of a name to indicate anything.
It could be better to remove the checks for word boundaries entirely.

### CODE REVIEW

**Comment by flovo** [comment]
Before I start adding hundreds of Unicode characters which could follow direct after username, what about simply checking for word boundaries (\b) after a username?

**Comment by anoek** [comment]
Yeah that seems like it should work? I'm not sure why I didn't do that to begin with...

**Comment by flovo** [comment]
It seems to work
image

**Comment by flovo** [comment]
image

**Comment by anoek** [comment]
Thanks for the PR!

**Pull request merged**
