### PR TITLE
Say in the console why we are getting 400 from the server

### PR DESCRIPTION
**Pull request by GreenAsJade**
I thought declaring the `get` as void would basically quiet everything, but apparently not, so at least now it says in the console what's going on.

### CODE REVIEW

**Comment by GreenAsJade** [comment]
I think I'm not a fan of Uffuzzi comments in github issues ... it's a bit of unnecessary spam...

**Comment by BHydden** [comment]
> I think I'm not a fan of Uffuzzi comments in github issues ... it's a bit of unnecessary spam...

They're not in issues, only pull requests, and the link is to a live implementation of the committed code, so you don't have to clone everyone's repo to test if a new change breaks anything.

**Comment by GreenAsJade** [comment]
Yeah, I know what they are, but it's a shame that they appear as comments, which send email notification...

**Comment by BHydden** [comment]
Only one per PR 🤷‍♂️ I think the benefit highly outweighs the (very slight) inconvenience personally

**Comment by GreenAsJade** [comment]
No each email in this discussion is unique.

I wonder if we could throw Uffuzi into the build pipeline and have the URL always available in the build check details...

**Comment by anoek** [comment]
Thanks for the clarification!

**Comment by GreenAsJade** [comment]
I realised just now that the reason Uffuzi emails are a pain in the neck is because it used to be the case that when you get an email from git immediately after a PR, it's because the build failed.

Now I get an email from git, and it's "whoa - what! .... Oh, that again".

**Comment by BHydden** [comment]
You don't sit on the git page waiting for the test to finish? Wow what confidence!  😅

**Comment by GreenAsJade** [comment]
It takes quite a while these days...

**Pull request merged**
