### PR TITLE
Make no autostart be a '-' instead of 'no', for contrast with handicap

### PR DESCRIPTION
**Pull request by GreenAsJade**
Fixes confusion between which column is which

## Proposed Changes

  Make no autostart be a '-' instead of 'no

### CODE REVIEW

**Comment by benjaminpjones** [comment]
aw missed opportunity for ∞ 😋

**Comment by GreenAsJade** [comment]
I was lining you up for the dream: a one character PR!

**Comment by benjaminpjones** [comment]
[Already covered!](https://github.com/online-go/online-go.com/pull/1698)

**Comment by anoek** [comment]
Good improvement, thanks!

**Pull request merged**
