### PR TITLE
Make autoplay delay configurable

### PR DESCRIPTION
**Pull request by mlopezviedma**
Adds an **Autoplay delay (in seconds)** option on Settings.

### CODE REVIEW

**Comment by anoek** [comment]
Nice :) Can we change this to allow for fractional seconds as well? Maybe add `step=0.1` for the number field, and then just swap out those `parseInt` calls for `parseFloat`, that aughta do it?

**Comment by anoek** [comment]
Also probably bound that to min of say 0.1, so we don't have folks setting 0 or negative values and then reporting bugs because autoplay "just jumps to the end" or something :)

**Comment by mlopezviedma** [comment]
That sounds a lot better :) On it.

**Comment by anoek** [comment]
Awesome :)

**Pull request merged**
