### PR TITLE
Remove unused ip widget

### PR DESCRIPTION
**Pull request by benjaminpjones**
Removing 200+ lines of code, mostly JSX.

### CODE REVIEW

**Comment by BHydden** [comment]
hmm 🤔  you sure this is unused? We have something very similar...

**Comment by anoek** [comment]
Pretty sure it is, I think we used to use it before we added the other moderator information on the profile pages or something? I haven't seen it in awhile.

**Comment by BHydden** [comment]
aah... I wasn't sure if he just wasn't seeing the mod section or if the code was duplicated at some point

**Comment by benjaminpjones** [comment]
@BHydden the mod section you're probably thinking of lives in ModTools.tsx.  

That said, if you notice something disappears, let me know!

**Comment by anoek** [comment]
Thanks for the cleanup!

**Pull request merged**
