### PR TITLE
Added profile button to Navigation Bar

### PR DESCRIPTION
**Pull request by briank621**
Requested from:
https://forums.online-go.com/t/putting-profile-button-on-top-menu-bar/12711

### CODE REVIEW

**Comment by anoek** [comment]
My gut says this link would be better under the little profile icon... but hard to visualize that being nice with what's currently under there so maybe it's fine on the main bar, though it may get reorganized later if we clean up the profile icon drop down at some point.

**Comment by briank621** [comment]
One idea I have is clicking on the profile picture goes to the profile, while the drop down remains the same.

**Comment by anoek** [comment]
Well, the other functionality there would then be a bit awkward - checking
notifications shouldn't ever change your page, and the quick theme change
stuff would also be out of place

**Comment by mlopezviedma** [comment]
What about adding one icon? Profile pic links to profile, and on the right, a gear/bell icon drops down the notification and theme area.

**Comment by anoek** [comment]
Yeah, the problem is primarily on mobile where there is very limited space up there. We'd have to see how it looks, I'm not opposed to trying though.

**Pull request merged**
