### PR TITLE
Resolve issue #468 ; add date hover text in chat backlog

### PR DESCRIPTION
**Pull request by MartijnTheunissen**
Resolve issue #468. Hover text with the full date was added for timestamp in the chat.

### CODE REVIEW

**Comment by arnaudgo** [comment]
Hello !

I'm happy you submited a MR for fixing the issue I opened :-)
Does it appear while hovering the mouse on the log entry?
I understand that and I feel a bit frustrated because most of the time, I visit OGS from my mobile.
But, I hope many desktop ogs users will enjoy your commit if it's accepted :-)

Arnaud

**Comment by MartijnTheunissen** [comment]
Hi!

You are correct, it appears while hovering a mouse over the entry.
I'm sorry you feel frustrated, what would you have rather seen?

Another format? If so which one? I was afraid it would take up too much space.
Otherwise I could look into a hover effect for mobile users if you would like that.

**Comment by arnaudgo** [comment]
I was thinking of a separation line every time a new starts (with the new date within it).

What do you think?

Arnaud

**Comment by MartijnTheunissen** [comment]
That seems like an elegant solution, I'll have a look at that.

**Comment by anoek** [comment]
Awesome, thanks for working on this! Yeah a date line separator would be awesome. We do something similar in the game chat page: https://github.com/online-go/online-go.com/blob/0f09c5e1d977c40df27809889abbe8f44dbb22af/src/views/Game/Game.tsx#L2980-L2986 if that's of any use to reference.

**Comment by MartijnTheunissen** [comment]
separator

This is how it looks like now :)

**Comment by anoek** [comment]
Awesome, looks great! I'm on the road for a few days, I'll do a full review and get this merged when I arrive, thanks for the PR!

**Pull request merged**
