### PR TITLE
Added basic warning for the time settings used by cheats

### PR DESCRIPTION
**Pull request by GreenAsJade**
Implements #716

### CODE REVIEW

**Comment by anoek** [comment]
I'm certainly open to this idea but I'm not so sure *all* absolute games are cheater games, nor *all* games with minimal main time are either.. for instance Canadian clocks could certainly have a low main time and still have reasonable time settings.

**Comment by GreenAsJade** [comment]
I think it's important to note that this in no way asserts than any given challenge _is_ a cheater game.  It just alerts people that some _might be_ used that way against them.

The other thing to note is that I see this as the framework for building a set of rules about what needs to be warned.   I'm certainly hazy on things like Canadian - I agree that there are bound to be some settings with minimal main time that make sense.

And, I guess that if you were going to cheat with Absolute time at the end, you wouldn't bother making a really long one.

So I'll try to think of some sensible refinements and resubmit :)

**Comment by anoek** [comment]
Cool I think we're almost there, my only note now is that we should make those strings translatable :) That's pretty much just a matter of wrapping them in an underscore call: `_("blah blah")`

**Comment by GreenAsJade** [comment]
Oh doh!  I knew that!

**Comment by anoek** [comment]
Awesome, thanks!

**Pull request merged**
