### PR TITLE
Filter challenges #601

### PR DESCRIPTION
**Pull request by GreenAsJade**
(apologies some spurious formatting changes got included in the source code, my editor auto format went nuts)

screenshot 2018-03-25 14 58 18 2

screenshot 2018-03-25 15 02 51 2

### CODE REVIEW

**Comment by lemurek** [comment]
This PR is showing 4 commits being included. I'm not a regular user of github, so I'm not sure what went wrong, but is it possible that you've included a bit more than you wanted in the PR ? 

You might want to rebase and squash your filter-challenges branch on the HEAD of main repo before submitting, to make it clearer.

**Comment by GreenAsJade** [comment]
I made it a little messy getting my fork up to date.

Maybe I should have done something like your suggestion to clean it up.  There's nothing else in there though.

**Comment by mlopezviedma** [comment]
Great! Although I would put the filter at the top, so you don't have to scroll down to change it.

**Comment by GreenAsJade** [comment]
It's at the bottom so it's mostly not visual clutter.

Since it's usually "unchecked", you don't have to scroll down to see it, because there's usually not much in the list (see first picture).

If you check it then the list grows, and true you need to scroll down to see it again, but I guess if you turned it on, then you wanted to scroll and look at all those anyhow?

I prefer it tidily out the way at the bottom.

**Comment by anoek** [comment]
Nice :) I took the liberty of moving that div outside of the table (looks and works the same, it just prevents  word wrapping when there are challenges with long names, it was getting treated like a table cell and got squished with the accept column)

**Pull request merged**
