### PR TITLE
Update Report.tsx

### PR DESCRIPTION
**Pull request by Sofia-mal**
Small changes.

### CODE REVIEW

**Comment by BHydden** [comment]
I think harassment is usefully distinct from inappropriate content and doesn't need to be removed.

Rest of the changes look pretty good though 👍

**Comment by Sofia-mal** [comment]
I think I'm giving up. If it is easy to fix and makes sense do it, otherwise close it. 

Regarding "inappropriate content" and "harassment" I think that making only one category makes sense. I wouldn't know which one to choose for a user that swears in chat. But 2 is fine too I guess.

**Comment by Sofia-mal** [comment]
I thought it was an easy thing to do from the web. It's a space/header problem again though. Sorry.

**Comment by BHydden** [comment]
Before the first error, one line was fine but you needed a space after the comma. I think that is the only problem code-wise? 🤔

**Comment by BHydden** [comment]
Re: types as I see it

Inappropriate content: one bad isolated incident (such as swearing or other abuse)
Harassment: prolonged behaviour where each incident might not be bad in isolation but represents a pattern of negative directed behaviour

**Comment by Sofia-mal** [comment]
> Before the first error, one line was fine but you needed a space after the comma. I think that is the only problem code-wise? 🤔

I don't know, but I am not going to try again today.



> Re: types as I see it
> 
> Inappropriate content: one bad isolated incident (such as swearing or other abuse) Harassment: prolonged behaviour where each incident might not be bad in isolation but represents a pattern of negative directed behaviour

It makes sense, but then the cases of 'harassement' are very rare indeed and perhaps can be included in 'other'. 
I have seen several confused users, now that I think about it. And some  still use "stalling" for escaping cases.

**Comment by Sofia-mal** [comment]
Finally seems ok. Sorry for my stupidity.

**Comment by benjaminpjones** [comment]
Argh it shouldn't be this hard. Prettier/formatting is great for adding consistency to the codebase, but I see that it's painful for folks who are submitting through the web interface. Sorry for the trouble @Sofia-mal !

One idea: I recently submitted a [PR to typeshed](https://github.com/python/typeshed/pull/9324), and one of the cool things they had was a bot that automatically fixed lints and appended a commit. I can dig into that and see if it's easy enough to set up for this repo.

**Comment by anoek** [comment]
That sounds pretty slick

**Comment by anoek** [comment]
Thanks for the wording improvements @Sofia-mal !

**Pull request merged**
